image: node:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn lint:fix
            - yarn build
            - cp dist/index.html dist/200.html
            - yarn deploy
